apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatting-deployment
  labels:
    app: chatting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatting
  template:
    metadata:
      labels:
        app: chatting
    spec:
      containers:
      - name: chatting
        image: leeinhong9512/panda-chatting:b6a08d04cf2cb87728187dfb27a9d8a0876a3ffa
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: chatting-storage
          mountPath: /app
      volumes:
      - name: chatting-storage
        persistentVolumeClaim:
          claimName: chatting-pvc  # 수정: PVC 이름을 chatting-pvc로 변경
      nodeSelector:
        worker: was  # 노드 셀렉터 추가
---
apiVersion: v1
kind: Service
metadata:
  name: chatting-service
spec:
  selector:
    app: chatting
  ports:
    - protocol: TCP
      port: 8082  # 서비스에 노출되는 포트
      targetPort: 8081  # 파드에 포워딩되는 포트
      nodePort: 31100  # 변경 가능: 노드 포트 번호 (30000 ~ 32767 사이의 값을 선택)
  type: NodePort  # 서비스 유형을 NodePort로 변경
  
